// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakerShop.Api.Data;

#nullable disable

namespace SneakerShop.Api.Migrations
{
    [DbContext(typeof(SneakerShopDbContext))]
    [Migration("20260902052700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SneakerShop.Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Size")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Code = "NK-AF1-001",
                            Name = "Air Force 1",
                            Quantity = 10,
                            Size = 9m,
                            UnitPrice = 5495m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            Code = "AD-SMB-002",
                            Name = "Samba OG",
                            Quantity = 7,
                            Size = 8.5m,
                            UnitPrice = 6800m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "New Balance",
                            Code = "NB-574-003",
                            Name = "574 Core",
                            Quantity = 4,
                            Size = 10m,
                            UnitPrice = 6595m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
